window.DEALS = {
  "generated_at": "2026-06-21T08:07:38.210088Z",
  "routes_watched": 15,
  "deals": [
    {
      "id": "DEL-KTM",
      "origin": "DEL",
      "destination": "KTM",
      "origin_city": "Delhi",
      "dest_city": "Kathmandu",
      "price_inr": 18021,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "high",
      "airline": "",
      "stops": "Unknown",
      "depart_date": "2026-08-04",
      "return_date": "2026-08-18",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+DEL+to+KTM+on+2026-08-04+through+2026-08-18",
      "first_seen": "2026-06-15T22:35:14.461437Z",
      "last_updated": "2026-06-15T22:35:14.461437Z"
    },
    {
      "id": "BOM-BKK",
      "origin": "BOM",
      "destination": "BKK",
      "origin_city": "Mumbai",
      "dest_city": "Bangkok",
      "price_inr": 21803,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "high",
      "airline": "BOM\u2192BKK / BKK\u2192BOM",
      "stops": 0,
      "depart_date": "2026-09-09",
      "return_date": "2026-09-23",
      "google_flights_url": "https://www.google.com/travel/flights?tfs=GhoSCjIwMjYtMDktMDlqBRIDQk9NcgUSA0JLSxoaEgoyMDI2LTA5LTIzagUSA0JLS3IFEgNCT01CAQFIAZgBAw%3D%3D&hl=en&curr=INR",
      "fare_type": "separate_tickets",
      "outbound_airline": "BOM\u2192BKK",
      "outbound_stops": 0,
      "outbound_price_inr": 10596,
      "return_airline": "BKK\u2192BOM",
      "return_stops": 0,
      "return_price_inr": 11207,
      "outbound_legs": [
        {
          "from": "BOM",
          "to": "BKK",
          "date": "2026-09-09",
          "airline": "Thai Vietjet Air",
          "stops": 0,
          "price_inr": 10596
        }
      ],
      "return_legs": [
        {
          "from": "BKK",
          "to": "BOM",
          "date": "2026-09-23",
          "airline": "Thai Vietjet Air",
          "stops": 0,
          "price_inr": 11207
        }
      ],
      "first_seen": "2026-06-21T07:14:44.601731Z",
      "last_updated": "2026-06-21T07:14:44.601731Z"
    },
    {
      "id": "BLR-SIN",
      "origin": "BLR",
      "destination": "SIN",
      "origin_city": "Bengaluru",
      "dest_city": "Singapore",
      "price_inr": 22575,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "typical",
      "airline": "IndiGo",
      "stops": 0,
      "depart_date": "2026-09-03",
      "return_date": "2026-09-13",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+BLR+to+SIN+on+2026-09-03+through+2026-09-13",
      "first_seen": "2026-06-15T22:35:14.461437Z",
      "last_updated": "2026-06-15T22:35:14.461437Z"
    },
    {
      "id": "DEL-DXB",
      "origin": "DEL",
      "destination": "DXB",
      "origin_city": "Delhi",
      "dest_city": "Dubai",
      "price_inr": 32798,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "typical",
      "airline": "IndiGo",
      "stops": 0,
      "depart_date": "2026-07-10",
      "return_date": "2026-07-20",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+DEL+to+DXB+on+2026-07-10+through+2026-07-20",
      "first_seen": "2026-06-15T22:35:14.461437Z",
      "last_updated": "2026-06-15T22:35:14.461437Z"
    },
    {
      "id": "BOM-JED",
      "origin": "BOM",
      "destination": "JED",
      "origin_city": "Mumbai",
      "dest_city": "Jeddah",
      "price_inr": 35331,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "high",
      "airline": "SalamAir",
      "stops": 1,
      "depart_date": "2026-08-04",
      "return_date": "2026-08-14",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+BOM+to+JED+on+2026-08-04+through+2026-08-14",
      "first_seen": "2026-06-15T22:35:14.461437Z",
      "last_updated": "2026-06-15T22:35:14.461437Z"
    },
    {
      "id": "DEL-ALA",
      "origin": "DEL",
      "destination": "ALA",
      "origin_city": "Delhi",
      "dest_city": "Almaty",
      "price_inr": 38369,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "typical",
      "airline": "",
      "stops": "Unknown",
      "depart_date": "2026-08-04",
      "return_date": "2026-08-14",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+DEL+to+ALA+on+2026-08-04+through+2026-08-14",
      "first_seen": "2026-06-15T22:35:14.461437Z",
      "last_updated": "2026-06-15T22:35:14.461437Z"
    },
    {
      "id": "DEL-MED",
      "origin": "DEL",
      "destination": "MED",
      "origin_city": "Delhi",
      "dest_city": "Madinah",
      "price_inr": 38947,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "typical",
      "airline": "",
      "stops": "Unknown",
      "depart_date": "2026-08-04",
      "return_date": "2026-08-14",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+DEL+to+MED+on+2026-08-04+through+2026-08-14",
      "first_seen": "2026-06-15T22:35:14.461437Z",
      "last_updated": "2026-06-15T22:35:14.461437Z"
    },
    {
      "id": "DEL-MLE",
      "origin": "DEL",
      "destination": "MLE",
      "origin_city": "Delhi",
      "dest_city": "Male",
      "price_inr": 42405,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "high",
      "airline": "DEL\u2192MLE / MLE\u2192DEL",
      "stops": 0,
      "depart_date": "2026-09-09",
      "return_date": "2026-09-19",
      "google_flights_url": "https://www.google.com/travel/flights?tfs=GhoSCjIwMjYtMDktMDlqBRIDREVMcgUSA01MRRoaEgoyMDI2LTA5LTE5agUSA01MRXIFEgNERUxCAQFIAZgBAw%3D%3D&hl=en&curr=INR",
      "fare_type": "separate_tickets",
      "outbound_airline": "DEL\u2192MLE",
      "outbound_stops": 0,
      "outbound_price_inr": 17117,
      "return_airline": "MLE\u2192DEL",
      "return_stops": 0,
      "return_price_inr": 25288,
      "outbound_legs": [
        {
          "from": "DEL",
          "to": "MLE",
          "date": "2026-09-09",
          "airline": "SriLankan",
          "stops": 1,
          "price_inr": 17117
        }
      ],
      "return_legs": [
        {
          "from": "MLE",
          "to": "DEL",
          "date": "2026-09-19",
          "airline": "SriLankan",
          "stops": 1,
          "price_inr": 25288
        }
      ],
      "first_seen": "2026-06-21T08:07:38.210088Z",
      "last_updated": "2026-06-21T08:07:38.210088Z"
    },
    {
      "id": "DEL-DPS",
      "origin": "DEL",
      "destination": "DPS",
      "origin_city": "Delhi",
      "dest_city": "Bali",
      "price_inr": 43354,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "typical",
      "airline": "DEL\u2192KUL\u2192DPS / DPS\u2192SGN\u2192DEL",
      "stops": 2,
      "depart_date": "2026-09-09",
      "return_date": "2026-09-23",
      "google_flights_url": "https://www.google.com/travel/flights?tfs=GhoSCjIwMjYtMDktMDlqBRIDREVMcgUSA0tVTBoaEgoyMDI2LTA5LTA5agUSA0tVTHIFEgNEUFMaGhIKMjAyNi0wOS0yM2oFEgNEUFNyBRIDU0dOGhoSCjIwMjYtMDktMjNqBRIDU0dOcgUSA0RFTEIBAUgBmAED&hl=en&curr=INR",
      "fare_type": "virtual_interline",
      "outbound_airline": "DEL\u2192KUL\u2192DPS",
      "outbound_stops": 1,
      "outbound_price_inr": 21735,
      "return_airline": "DPS\u2192SGN\u2192DEL",
      "return_stops": 1,
      "return_price_inr": 21619,
      "outbound_legs": [
        {
          "from": "DEL",
          "to": "KUL",
          "date": "2026-09-09",
          "airline": "Batik Air",
          "stops": 0,
          "price_inr": 12411
        },
        {
          "from": "KUL",
          "to": "DPS",
          "date": "2026-09-09",
          "airline": "AirAsia",
          "stops": 0,
          "price_inr": 9324
        }
      ],
      "return_legs": [
        {
          "from": "DPS",
          "to": "SGN",
          "date": "2026-09-23",
          "airline": "Scoot",
          "stops": 1,
          "price_inr": 8568
        },
        {
          "from": "SGN",
          "to": "DEL",
          "date": "2026-09-23",
          "airline": "Vietjet",
          "stops": 1,
          "price_inr": 13051
        }
      ],
      "first_seen": "2026-06-21T08:07:38.210088Z",
      "last_updated": "2026-06-21T08:07:38.210088Z"
    },
    {
      "id": "DEL-JED",
      "origin": "DEL",
      "destination": "JED",
      "origin_city": "Delhi",
      "dest_city": "Jeddah",
      "price_inr": 45057,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "high",
      "airline": "",
      "stops": "Unknown",
      "depart_date": "2026-08-04",
      "return_date": "2026-08-14",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+DEL+to+JED+on+2026-08-04+through+2026-08-14",
      "first_seen": "2026-06-15T22:35:14.461437Z",
      "last_updated": "2026-06-15T22:35:14.461437Z"
    },
    {
      "id": "DEL-GYD",
      "origin": "DEL",
      "destination": "GYD",
      "origin_city": "Delhi",
      "dest_city": "Baku",
      "price_inr": 45633,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "typical",
      "airline": "Azerbaijan Airlines",
      "stops": 0,
      "depart_date": "2026-09-03",
      "return_date": "2026-09-17",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+DEL+to+GYD+on+2026-09-03+through+2026-09-17",
      "first_seen": "2026-06-15T22:35:14.461437Z",
      "last_updated": "2026-06-15T22:35:14.461437Z"
    },
    {
      "id": "LKO-JED",
      "origin": "LKO",
      "destination": "JED",
      "origin_city": "Lucknow",
      "dest_city": "Jeddah",
      "price_inr": 46814,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "high",
      "airline": "SalamAir",
      "stops": 1,
      "depart_date": "2026-09-03",
      "return_date": "2026-09-13",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+LKO+to+JED+on+2026-09-03+through+2026-09-13",
      "first_seen": "2026-06-15T22:35:14.461437Z",
      "last_updated": "2026-06-15T22:35:14.461437Z"
    },
    {
      "id": "DEL-TBS",
      "origin": "DEL",
      "destination": "TBS",
      "origin_city": "Delhi",
      "dest_city": "Tbilisi",
      "price_inr": 52067,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "high",
      "airline": "Gulf Air",
      "stops": 2,
      "depart_date": "2026-09-03",
      "return_date": "2026-09-17",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+DEL+to+TBS+on+2026-09-03+through+2026-09-17",
      "first_seen": "2026-06-15T22:35:14.461437Z",
      "last_updated": "2026-06-15T22:35:14.461437Z"
    },
    {
      "id": "DEL-NRT",
      "origin": "DEL",
      "destination": "NRT",
      "origin_city": "Delhi",
      "dest_city": "Tokyo",
      "price_inr": 55830,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "high",
      "airline": "DEL\u2192HKG\u2192NRT / NRT\u2192DEL",
      "stops": 1,
      "depart_date": "2026-09-09",
      "return_date": "2026-09-23",
      "google_flights_url": "https://www.google.com/travel/flights?tfs=GhoSCjIwMjYtMDktMDlqBRIDREVMcgUSA0hLRxoaEgoyMDI2LTA5LTEwagUSA0hLR3IFEgNOUlQaGhIKMjAyNi0wOS0yM2oFEgNOUlRyBRIDREVMQgEBSAGYAQM%3D&hl=en&curr=INR",
      "fare_type": "virtual_interline",
      "outbound_airline": "DEL\u2192HKG\u2192NRT",
      "outbound_stops": 1,
      "outbound_price_inr": 32865,
      "return_airline": "NRT\u2192DEL",
      "return_stops": 0,
      "return_price_inr": 22965,
      "outbound_legs": [
        {
          "from": "DEL",
          "to": "HKG",
          "date": "2026-09-09",
          "airline": "Malaysia Airlines",
          "stops": 1,
          "price_inr": 18611
        },
        {
          "from": "HKG",
          "to": "NRT",
          "date": "2026-09-10",
          "airline": "Hong Kong Express",
          "stops": 0,
          "price_inr": 14254
        }
      ],
      "return_legs": [
        {
          "from": "NRT",
          "to": "DEL",
          "date": "2026-09-23",
          "airline": "Vietjet",
          "stops": 1,
          "price_inr": 22965
        }
      ],
      "first_seen": "2026-06-21T08:07:38.210088Z",
      "last_updated": "2026-06-21T08:07:38.210088Z"
    },
    {
      "id": "DEL-ZRH",
      "origin": "DEL",
      "destination": "ZRH",
      "origin_city": "Delhi",
      "dest_city": "Zurich",
      "price_inr": 62920,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "high",
      "airline": "DEL\u2192ZRH / ZRH\u2192DEL",
      "stops": 0,
      "depart_date": "2026-08-10",
      "return_date": "2026-08-24",
      "google_flights_url": "https://www.google.com/travel/flights?tfs=GhoSCjIwMjYtMDgtMTBqBRIDREVMcgUSA1pSSBoaEgoyMDI2LTA4LTI0agUSA1pSSHIFEgNERUxCAQFIAZgBAw%3D%3D&hl=en&curr=INR",
      "fare_type": "separate_tickets",
      "outbound_airline": "DEL\u2192ZRH",
      "outbound_stops": 0,
      "outbound_price_inr": 33697,
      "return_airline": "ZRH\u2192DEL",
      "return_stops": 0,
      "return_price_inr": 29223,
      "outbound_legs": [
        {
          "from": "DEL",
          "to": "ZRH",
          "date": "2026-08-10",
          "airline": "Emirates",
          "stops": 1,
          "price_inr": 33697
        }
      ],
      "return_legs": [
        {
          "from": "ZRH",
          "to": "DEL",
          "date": "2026-08-24",
          "airline": "Etihad",
          "stops": 1,
          "price_inr": 29223
        }
      ],
      "first_seen": "2026-06-21T08:07:38.210088Z",
      "last_updated": "2026-06-21T08:07:38.210088Z"
    }
  ]
};
