window.DEALS = {
  "generated_at": "2026-06-15T21:38:00.224987Z",
  "routes_watched": 12,
  "deals": [
    {
      "id": "DEL-KTM",
      "origin": "DEL",
      "destination": "KTM",
      "origin_city": "Delhi",
      "dest_city": "Kathmandu",
      "price_inr": 18001,
      "typical_inr": 61920,
      "drop_pct": 71,
      "savings_inr": 43919,
      "family_savings_inr": 175676,
      "lowest_in_days": null,
      "typical_source": "history",
      "google_signal": "high",
      "airline": "",
      "stops": "Unknown",
      "depart_date": "2026-08-04",
      "return_date": "2026-08-18",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+DEL+to+KTM+on+2026-08-04+through+2026-08-18"
    },
    {
      "id": "DEL-ALA",
      "origin": "DEL",
      "destination": "ALA",
      "origin_city": "Delhi",
      "dest_city": "Almaty",
      "price_inr": 38369,
      "typical_inr": 130725,
      "drop_pct": 71,
      "savings_inr": 92356,
      "family_savings_inr": 369424,
      "lowest_in_days": null,
      "typical_source": "history",
      "google_signal": "typical",
      "airline": "",
      "stops": "Unknown",
      "depart_date": "2026-08-04",
      "return_date": "2026-08-14",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+DEL+to+ALA+on+2026-08-04+through+2026-08-14"
    },
    {
      "id": "BOM-BKK",
      "origin": "BOM",
      "destination": "BKK",
      "origin_city": "Mumbai",
      "dest_city": "Bangkok",
      "price_inr": 24069,
      "typical_inr": 67957,
      "drop_pct": 65,
      "savings_inr": 43888,
      "family_savings_inr": 175552,
      "lowest_in_days": null,
      "typical_source": "history",
      "google_signal": "high",
      "airline": "",
      "stops": "Unknown",
      "depart_date": "2026-08-04",
      "return_date": "2026-08-18",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+BOM+to+BKK+on+2026-08-04+through+2026-08-18"
    },
    {
      "id": "DEL-MED",
      "origin": "DEL",
      "destination": "MED",
      "origin_city": "Delhi",
      "dest_city": "Madinah",
      "price_inr": 38947,
      "typical_inr": 111890,
      "drop_pct": 65,
      "savings_inr": 72943,
      "family_savings_inr": 291772,
      "lowest_in_days": null,
      "typical_source": "history",
      "google_signal": "typical",
      "airline": "",
      "stops": "Unknown",
      "depart_date": "2026-08-04",
      "return_date": "2026-08-14",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+DEL+to+MED+on+2026-08-04+through+2026-08-14"
    },
    {
      "id": "BLR-SIN",
      "origin": "BLR",
      "destination": "SIN",
      "origin_city": "Bengaluru",
      "dest_city": "Singapore",
      "price_inr": 22575,
      "typical_inr": 58941,
      "drop_pct": 62,
      "savings_inr": 36366,
      "family_savings_inr": 145464,
      "lowest_in_days": null,
      "typical_source": "history",
      "google_signal": "typical",
      "airline": "",
      "stops": "Unknown",
      "depart_date": "2026-09-03",
      "return_date": "2026-09-13",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+BLR+to+SIN+on+2026-09-03+through+2026-09-13"
    },
    {
      "id": "DEL-DPS",
      "origin": "DEL",
      "destination": "DPS",
      "origin_city": "Delhi",
      "dest_city": "Bali",
      "price_inr": 33133,
      "typical_inr": 84306,
      "drop_pct": 61,
      "savings_inr": 51173,
      "family_savings_inr": 204692,
      "lowest_in_days": 55,
      "typical_source": "history",
      "google_signal": "typical",
      "airline": "Batik Air",
      "stops": 1,
      "depart_date": "2026-09-03",
      "return_date": "2026-09-13",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+DEL+to+DPS+on+2026-09-03+through+2026-09-13"
    },
    {
      "id": "DEL-GYD",
      "origin": "DEL",
      "destination": "GYD",
      "origin_city": "Delhi",
      "dest_city": "Baku",
      "price_inr": 45633,
      "typical_inr": 88129,
      "drop_pct": 48,
      "savings_inr": 42496,
      "family_savings_inr": 169984,
      "lowest_in_days": null,
      "typical_source": "history",
      "google_signal": "typical",
      "airline": "",
      "stops": "Unknown",
      "depart_date": "2026-09-03",
      "return_date": "2026-09-17",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+DEL+to+GYD+on+2026-09-03+through+2026-09-17"
    },
    {
      "id": "BOM-JED",
      "origin": "BOM",
      "destination": "JED",
      "origin_city": "Mumbai",
      "dest_city": "Jeddah",
      "price_inr": 35331,
      "typical_inr": 63406,
      "drop_pct": 44,
      "savings_inr": 28075,
      "family_savings_inr": 112300,
      "lowest_in_days": null,
      "typical_source": "history",
      "google_signal": "high",
      "airline": "SalamAir",
      "stops": 1,
      "depart_date": "2026-08-04",
      "return_date": "2026-08-14",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+BOM+to+JED+on+2026-08-04+through+2026-08-14"
    },
    {
      "id": "DEL-TBS",
      "origin": "DEL",
      "destination": "TBS",
      "origin_city": "Delhi",
      "dest_city": "Tbilisi",
      "price_inr": 52067,
      "typical_inr": 92143,
      "drop_pct": 43,
      "savings_inr": 40076,
      "family_savings_inr": 160304,
      "lowest_in_days": null,
      "typical_source": "history",
      "google_signal": "high",
      "airline": "Gulf Air",
      "stops": 2,
      "depart_date": "2026-09-03",
      "return_date": "2026-09-17",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+DEL+to+TBS+on+2026-09-03+through+2026-09-17"
    },
    {
      "id": "DEL-DXB",
      "origin": "DEL",
      "destination": "DXB",
      "origin_city": "Delhi",
      "dest_city": "Dubai",
      "price_inr": 32798,
      "typical_inr": 55615,
      "drop_pct": 41,
      "savings_inr": 22817,
      "family_savings_inr": 91268,
      "lowest_in_days": null,
      "typical_source": "history",
      "google_signal": "typical",
      "airline": "IndiGo",
      "stops": 0,
      "depart_date": "2026-07-10",
      "return_date": "2026-07-20",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+DEL+to+DXB+on+2026-07-10+through+2026-07-20"
    },
    {
      "id": "DEL-JED",
      "origin": "DEL",
      "destination": "JED",
      "origin_city": "Delhi",
      "dest_city": "Jeddah",
      "price_inr": 45057,
      "typical_inr": 73114,
      "drop_pct": 38,
      "savings_inr": 28057,
      "family_savings_inr": 112228,
      "lowest_in_days": null,
      "typical_source": "history",
      "google_signal": "high",
      "airline": "Air India",
      "stops": 0,
      "depart_date": "2026-08-04",
      "return_date": "2026-08-14",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+DEL+to+JED+on+2026-08-04+through+2026-08-14"
    }
  ]
};
