window.DEALS = {
  "generated_at": "2026-06-23T06:31:18.602547Z",
  "routes_watched": 15,
  "deals": [
    {
      "id": "DEL-KTM",
      "origin": "DEL",
      "destination": "KTM",
      "origin_city": "Delhi",
      "dest_city": "Kathmandu",
      "price_inr": 18021,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "high",
      "airline": "",
      "stops": "Unknown",
      "depart_date": "2026-08-04",
      "return_date": "2026-08-18",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+DEL+to+KTM+on+2026-08-04+through+2026-08-18",
      "first_seen": "2026-06-15T22:35:14.461437Z",
      "last_updated": "2026-06-15T22:35:14.461437Z"
    },
    {
      "id": "BLR-SIN",
      "origin": "BLR",
      "destination": "SIN",
      "origin_city": "Bengaluru",
      "dest_city": "Singapore",
      "price_inr": 22575,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "typical",
      "airline": "IndiGo",
      "stops": 0,
      "depart_date": "2026-09-03",
      "return_date": "2026-09-13",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+BLR+to+SIN+on+2026-09-03+through+2026-09-13",
      "first_seen": "2026-06-15T22:35:14.461437Z",
      "last_updated": "2026-06-15T22:35:14.461437Z"
    },
    {
      "id": "BOM-BKK",
      "origin": "BOM",
      "destination": "BKK",
      "origin_city": "Mumbai",
      "dest_city": "Bangkok",
      "price_inr": 23386,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "high",
      "airline": "BOM\u2192BKK / BKK\u2192BOM",
      "stops": 0,
      "depart_date": "2026-09-10",
      "return_date": "2026-09-20",
      "google_flights_url": "https://www.google.com/travel/flights?tfs=GhoSCjIwMjYtMDktMTBqBRIDQk9NcgUSA0JLSxoaEgoyMDI2LTA5LTIwagUSA0JLS3IFEgNCT01CAQFIAZgBAw%3D%3D&hl=en&curr=INR",
      "fare_type": "separate_tickets",
      "outbound_airline": "BOM\u2192BKK",
      "outbound_stops": 0,
      "outbound_price_inr": 10625,
      "return_airline": "BKK\u2192BOM",
      "return_stops": 0,
      "return_price_inr": 12761,
      "outbound_legs": [
        {
          "from": "BOM",
          "to": "BKK",
          "date": "2026-09-10",
          "airline": "Thai Vietjet Air",
          "stops": 0,
          "price_inr": 10625
        }
      ],
      "return_legs": [
        {
          "from": "BKK",
          "to": "BOM",
          "date": "2026-09-20",
          "airline": "Thai Vietjet Air",
          "stops": 0,
          "price_inr": 12761
        }
      ],
      "first_seen": "2026-06-22T08:35:28.485609Z",
      "last_updated": "2026-06-22T08:35:28.485609Z"
    },
    {
      "id": "DEL-DXB",
      "origin": "DEL",
      "destination": "DXB",
      "origin_city": "Delhi",
      "dest_city": "Dubai",
      "price_inr": 32798,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "typical",
      "airline": "IndiGo",
      "stops": 0,
      "depart_date": "2026-07-10",
      "return_date": "2026-07-20",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+DEL+to+DXB+on+2026-07-10+through+2026-07-20",
      "first_seen": "2026-06-15T22:35:14.461437Z",
      "last_updated": "2026-06-15T22:35:14.461437Z"
    },
    {
      "id": "BOM-JED",
      "origin": "BOM",
      "destination": "JED",
      "origin_city": "Mumbai",
      "dest_city": "Jeddah",
      "price_inr": 35331,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "high",
      "airline": "SalamAir",
      "stops": 1,
      "depart_date": "2026-08-04",
      "return_date": "2026-08-14",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+BOM+to+JED+on+2026-08-04+through+2026-08-14",
      "first_seen": "2026-06-15T22:35:14.461437Z",
      "last_updated": "2026-06-15T22:35:14.461437Z"
    },
    {
      "id": "DEL-ALA",
      "origin": "DEL",
      "destination": "ALA",
      "origin_city": "Delhi",
      "dest_city": "Almaty",
      "price_inr": 38369,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "typical",
      "airline": "",
      "stops": "Unknown",
      "depart_date": "2026-08-04",
      "return_date": "2026-08-14",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+DEL+to+ALA+on+2026-08-04+through+2026-08-14",
      "first_seen": "2026-06-15T22:35:14.461437Z",
      "last_updated": "2026-06-15T22:35:14.461437Z"
    },
    {
      "id": "DEL-MED",
      "origin": "DEL",
      "destination": "MED",
      "origin_city": "Delhi",
      "dest_city": "Madinah",
      "price_inr": 38947,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "typical",
      "airline": "",
      "stops": "Unknown",
      "depart_date": "2026-08-04",
      "return_date": "2026-08-14",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+DEL+to+MED+on+2026-08-04+through+2026-08-14",
      "first_seen": "2026-06-15T22:35:14.461437Z",
      "last_updated": "2026-06-15T22:35:14.461437Z"
    },
    {
      "id": "DEL-DPS",
      "origin": "DEL",
      "destination": "DPS",
      "origin_city": "Delhi",
      "dest_city": "Bali",
      "price_inr": 39730,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "typical",
      "airline": "DEL\u2192KUL\u2192DPS / DPS\u2192DEL",
      "stops": 1,
      "depart_date": "2026-08-12",
      "return_date": "2026-08-26",
      "google_flights_url": "https://www.google.com/travel/flights?tfs=GhoSCjIwMjYtMDgtMTJqBRIDREVMcgUSA0tVTBoaEgoyMDI2LTA4LTEyagUSA0tVTHIFEgNEUFMaGhIKMjAyNi0wOC0yNmoFEgNEUFNyBRIDREVMQgEBSAGYAQM%3D&hl=en&curr=INR",
      "fare_type": "virtual_interline",
      "outbound_airline": "DEL\u2192KUL\u2192DPS",
      "outbound_stops": 1,
      "outbound_price_inr": 19782,
      "return_airline": "DPS\u2192DEL",
      "return_stops": 0,
      "return_price_inr": 19948,
      "outbound_legs": [
        {
          "from": "DEL",
          "to": "KUL",
          "date": "2026-08-12",
          "airline": "AirAsia X",
          "stops": 0,
          "price_inr": 12012
        },
        {
          "from": "KUL",
          "to": "DPS",
          "date": "2026-08-12",
          "airline": "Scoot",
          "stops": 1,
          "price_inr": 7770
        }
      ],
      "return_legs": [
        {
          "from": "DPS",
          "to": "DEL",
          "date": "2026-08-26",
          "airline": "Vietjet",
          "stops": 1,
          "price_inr": 19948
        }
      ],
      "first_seen": "2026-06-23T06:31:18.602547Z",
      "last_updated": "2026-06-23T06:31:18.602547Z"
    },
    {
      "id": "DEL-MLE",
      "origin": "DEL",
      "destination": "MLE",
      "origin_city": "Delhi",
      "dest_city": "Male",
      "price_inr": 44826,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "high",
      "airline": "DEL\u2192BLR\u2192MLE / MLE\u2192DEL",
      "stops": 1,
      "depart_date": "2026-09-11",
      "return_date": "2026-09-21",
      "google_flights_url": "https://www.google.com/travel/flights?tfs=GhoSCjIwMjYtMDktMTFqBRIDREVMcgUSA0JMUhoaEgoyMDI2LTA5LTExagUSA0JMUnIFEgNNTEUaGhIKMjAyNi0wOS0yMWoFEgNNTEVyBRIDREVMQgEBSAGYAQM%3D&hl=en&curr=INR",
      "fare_type": "virtual_interline",
      "outbound_airline": "DEL\u2192BLR\u2192MLE",
      "outbound_stops": 1,
      "outbound_price_inr": 19449,
      "return_airline": "MLE\u2192DEL",
      "return_stops": 0,
      "return_price_inr": 25377,
      "outbound_legs": [
        {
          "from": "DEL",
          "to": "BLR",
          "date": "2026-09-11",
          "airline": "IndiGo",
          "stops": 1,
          "price_inr": 7419
        },
        {
          "from": "BLR",
          "to": "MLE",
          "date": "2026-09-11",
          "airline": "SriLankan",
          "stops": 1,
          "price_inr": 12030
        }
      ],
      "return_legs": [
        {
          "from": "MLE",
          "to": "DEL",
          "date": "2026-09-21",
          "airline": "SriLankan",
          "stops": 1,
          "price_inr": 25377
        }
      ],
      "first_seen": "2026-06-23T06:31:18.602547Z",
      "last_updated": "2026-06-23T06:31:18.602547Z"
    },
    {
      "id": "DEL-JED",
      "origin": "DEL",
      "destination": "JED",
      "origin_city": "Delhi",
      "dest_city": "Jeddah",
      "price_inr": 45057,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "high",
      "airline": "",
      "stops": "Unknown",
      "depart_date": "2026-08-04",
      "return_date": "2026-08-14",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+DEL+to+JED+on+2026-08-04+through+2026-08-14",
      "first_seen": "2026-06-15T22:35:14.461437Z",
      "last_updated": "2026-06-15T22:35:14.461437Z"
    },
    {
      "id": "DEL-GYD",
      "origin": "DEL",
      "destination": "GYD",
      "origin_city": "Delhi",
      "dest_city": "Baku",
      "price_inr": 45633,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "typical",
      "airline": "Azerbaijan Airlines",
      "stops": 0,
      "depart_date": "2026-09-03",
      "return_date": "2026-09-17",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+DEL+to+GYD+on+2026-09-03+through+2026-09-17",
      "first_seen": "2026-06-15T22:35:14.461437Z",
      "last_updated": "2026-06-15T22:35:14.461437Z"
    },
    {
      "id": "DEL-NRT",
      "origin": "DEL",
      "destination": "NRT",
      "origin_city": "Delhi",
      "dest_city": "Tokyo",
      "price_inr": 45926,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "typical",
      "airline": "DEL\u2192NRT / NRT\u2192DEL",
      "stops": 0,
      "depart_date": "2026-09-11",
      "return_date": "2026-09-25",
      "google_flights_url": "https://www.google.com/travel/flights?tfs=GhoSCjIwMjYtMDktMTFqBRIDREVMcgUSA05SVBoaEgoyMDI2LTA5LTI1agUSA05SVHIFEgNERUxCAQFIAZgBAw%3D%3D&hl=en&curr=INR",
      "fare_type": "separate_tickets",
      "outbound_airline": "DEL\u2192NRT",
      "outbound_stops": 0,
      "outbound_price_inr": 25961,
      "return_airline": "NRT\u2192DEL",
      "return_stops": 0,
      "return_price_inr": 19965,
      "outbound_legs": [
        {
          "from": "DEL",
          "to": "NRT",
          "date": "2026-09-11",
          "airline": "Vietjet",
          "stops": 1,
          "price_inr": 25961
        }
      ],
      "return_legs": [
        {
          "from": "NRT",
          "to": "DEL",
          "date": "2026-09-25",
          "airline": "Vietjet",
          "stops": 1,
          "price_inr": 19965
        }
      ],
      "first_seen": "2026-06-23T06:31:18.602547Z",
      "last_updated": "2026-06-23T06:31:18.602547Z"
    },
    {
      "id": "LKO-JED",
      "origin": "LKO",
      "destination": "JED",
      "origin_city": "Lucknow",
      "dest_city": "Jeddah",
      "price_inr": 46814,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "high",
      "airline": "SalamAir",
      "stops": 1,
      "depart_date": "2026-09-03",
      "return_date": "2026-09-13",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+LKO+to+JED+on+2026-09-03+through+2026-09-13",
      "first_seen": "2026-06-15T22:35:14.461437Z",
      "last_updated": "2026-06-15T22:35:14.461437Z"
    },
    {
      "id": "DEL-TBS",
      "origin": "DEL",
      "destination": "TBS",
      "origin_city": "Delhi",
      "dest_city": "Tbilisi",
      "price_inr": 52067,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "high",
      "airline": "Gulf Air",
      "stops": 2,
      "depart_date": "2026-09-03",
      "return_date": "2026-09-17",
      "google_flights_url": "https://www.google.com/travel/flights?q=Flights+from+DEL+to+TBS+on+2026-09-03+through+2026-09-17",
      "first_seen": "2026-06-15T22:35:14.461437Z",
      "last_updated": "2026-06-15T22:35:14.461437Z"
    },
    {
      "id": "DEL-ZRH",
      "origin": "DEL",
      "destination": "ZRH",
      "origin_city": "Delhi",
      "dest_city": "Zurich",
      "price_inr": 62914,
      "typical_inr": null,
      "drop_pct": null,
      "savings_inr": null,
      "family_savings_inr": null,
      "lowest_in_days": null,
      "typical_source": "cheapest_ever",
      "google_signal": "typical",
      "airline": "DEL\u2192ZRH / ZRH\u2192DEL",
      "stops": 0,
      "depart_date": "2026-08-11",
      "return_date": "2026-08-25",
      "google_flights_url": "https://www.google.com/travel/flights?tfs=GhoSCjIwMjYtMDgtMTFqBRIDREVMcgUSA1pSSBoaEgoyMDI2LTA4LTI1agUSA1pSSHIFEgNERUxCAQFIAZgBAw%3D%3D&hl=en&curr=INR",
      "fare_type": "separate_tickets",
      "outbound_airline": "DEL\u2192ZRH",
      "outbound_stops": 0,
      "outbound_price_inr": 33697,
      "return_airline": "ZRH\u2192DEL",
      "return_stops": 0,
      "return_price_inr": 29217,
      "outbound_legs": [
        {
          "from": "DEL",
          "to": "ZRH",
          "date": "2026-08-11",
          "airline": "Emirates",
          "stops": 1,
          "price_inr": 33697
        }
      ],
      "return_legs": [
        {
          "from": "ZRH",
          "to": "DEL",
          "date": "2026-08-25",
          "airline": "Etihad",
          "stops": 1,
          "price_inr": 29217
        }
      ],
      "first_seen": "2026-06-22T08:35:28.485609Z",
      "last_updated": "2026-06-22T08:35:28.485609Z"
    }
  ]
};
